---
title: "Introduction"
subtitle: "Spring 2026"
format: 
  html:
    page-layout: full
    theme: cosmo
    toc: true
    toc-title: "Contents"
    embed-resources: true
    standalone: true
editor: 
  markdown: 
    wrap: 72
---

In the music industry, there is a long-standing debate: is a song's success driven by its quantifiable musical characteristics, or is it a product of "unmeasurables" like marketing, catchiness, pure luck, and good timing, among others?

Our project seeks to address this by analyzing a comprehensive sample of hit and non-hit songs released between **2010 and 2019**. We define a "hit" specifically as any song that made an appearance on the **Billboard Hot 100** at some point after its release.

### Why the 2010s?

We chose to focus on the 2010s for several reasons:

* **Formative Years**: This decade represents the childhood and teenage years for many in our generation, meaning the music resonates with many of us.

* **Lasting Impact**: The music from this era was exceptionally high-quality and "timeless", with many tracks still charting or receiving many streams today.

* **Shifting Trends**: The criteria for what makes a song "successful" appeared to undergo significant shifts during this decade compared to those preceding it.

### Our Goal

The primary objective of this study is to predict the charting success of 2010s songs based on solely their audio characteristics and genre classifications. We aimed to build a classification model capable of differentiating hit songs from non-hit songs with over **50% accuracy** consistently (better than just random guessing!).

### Hypotheses

Going into our modeling phase, we developed two sets of expectations regarding Spotify's audio features:

1. **Predictors of Success**: We hypothesized that higher **danceability**, **valence** (musical positiveness), and **loudness** would increase a song's likelihood of becoming a hit. We also expected **pop** and **hip hop/rap** tracks to be the driving genres of success since the two seemed to take over the mainstream during this period. We also expected **soundtrack** music to indicate success and these usually feature popular artists and are well-funded and marketed. Conversely, we expected lower **duration**, **acousticness**, **speechiness** (level of spoken word), and **instrumentalness** (likelihood of being an instrumental track) to be associated with chart success. We also expected genres like **rock**, **folk**, and **classical** to indicate less successful songs, as there seem to be less popular songs of these genres during this period.

2. **Neutral Elements**: We predicted that features like **key**, **tempo**, **mode** (major or minor key), and whether a song is **explicit** would have little to no measurable effect on a song's probability of charting.

---

Next, we will dive into the **Data and Cleaning** process to show how we narrowed down nearly a million observations into a clean, balanced dataset for our analysis and modeling.